### ISSUE TITLE
v0.1.0 npm package broken?

### ISSUE THREAD

**Issue by kun432** [fx-adr/apla-responder#10]
I don't know much about JS/TS. So, sorry in advanced if I'm wrong.

v0.1.0 npm package seems broken.

```
$ npm install ask-sdk-core ask-sdk-model apla-responder
...snip...

+ apla-responder@0.1.0
+ ask-sdk-model@1.29.0
+ ask-sdk-core@2.9.0
added 4 packages from 4 contributors and audited 6 packages in 0.935s
found 0 vulnerabilities
```

```
$ ls node_modules/apla-responder/build/
index.js
```

For v0.1.0, loading apla-responder has failed.

```
$ node
> const Alexa = require('ask-sdk-core');
undefined
> const { AudioResponse, Components: Apla } = require('apla-responder');
Thrown:
{ Error: Cannot find module './generator/Generator'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18) code: 'MODULE_NOT_FOUND' }
>
```

For v0.0.1, no problem.

```
$ npm install ask-sdk-core ask-sdk-model apla-responder@0.0.1
...snip...
+ apla-responder@0.0.1
+ ask-sdk-core@2.9.0
+ ask-sdk-model@1.29.0
added 4 packages from 4 contributors and audited 4 packages in 0.849s
found 0 vulnerabilities
```

```
$ ls node_modules/apla-responder/build/
apla-documents	errors		generator	interfaces	library.js
components	filter-classes	index.js	jest.config.js	src
```

```
$ node
> const Alexa = require('ask-sdk-core');
undefined
> const { AudioResponse, Components: Apla } = require('apla-responder');
undefined
```

Anyway, this package is very AWESOME!

**Comment by allthepies** [comment]
Did you ever fix this ?  Would love to use the library but am getting the same error.
